import os
import sqlite3
from dotenv import load_dotenv

# --- 1. CONFIGURATION ---
load_dotenv()
STAGING_DIR = os.getenv("STAGING_DIR", "C:/vector_staging")
DB_PATH = os.path.join(STAGING_DIR, "manifest.db")

def check_gemini_status():
    if not os.path.exists(DB_PATH):
        print(f"❌ Could not find database at {DB_PATH}")
        return

    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    # 1. Count successfully completed PDFs
    cursor.execute("SELECT count(*) FROM manifest WHERE status = 'COMPLETED_GEMINI'")
    completed_pdfs = cursor.fetchone()[0]

    # 2. Count any PDFs that failed or are still waiting
    cursor.execute("SELECT count(*) FROM manifest WHERE status = 'API_ERROR'")
    error_pdfs = cursor.fetchone()[0]
    
    cursor.execute("SELECT count(*) FROM manifest WHERE status = 'APPROVED_FOR_EXTRACTION' AND route = 'ROUTE_GEMINI_MULTIMODAL'")
    pending_pdfs = cursor.fetchone()[0]

    # 3. Count the actual Semantic Blocks generated by Gemini
    cursor.execute("""
        SELECT count(*) FROM semantic_blocks 
        JOIN manifest ON semantic_blocks.manifest_id = manifest.id
        WHERE manifest.status = 'COMPLETED_GEMINI'
    """)
    total_blocks = cursor.fetchone()[0]

    # --- PRINT THE REPORT ---
    print("\n" + "="*45)
    print(" 📊 GEMINI EXTRACTION (07.0) DB REPORT 📊")
    print("="*45)
    print(f"✅ Successfully Processed PDFs : {completed_pdfs}")
    print(f"🧩 Semantic Blocks Generated   : {total_blocks}")
    print(f"⏳ Still Pending in Queue      : {pending_pdfs}")
    print(f"⚠️ API Errors Caught           : {error_pdfs}")
    print("="*45 + "\n")

    conn.close()

if __name__ == "__main__":
    check_gemini_status()